name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    strategy:
      max-parallel: 1
      matrix:
        platform: ["ubuntu-latest"]

    name: "Build wheels on ${{ matrix.platform }}"
    runs-on: "${{ matrix.platform }}"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.8"

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: "pp* cp27-* cp35-* cp36-* cp37-* *-manylinux_i686 *-win32 *musllinux*"
          CIBW_MANYLINUX_X86_64_IMAGE: "quay.io/pypa/manylinux_2_28_x86_64"
          CIBW_BEFORE_BUILD: "pip install ."
          CIBW_BEFORE_ALL_LINUX: "(yum install -y python3-devel || apt install -y python3-dev)"
          CIBW_BUILD_VERBOSITY: 2

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
